"""Change category

Revision ID: 3d895d15e832
Revises: b28d1c90569b
Create Date: 2023-12-17 19:48:55.469031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d895d15e832'
down_revision: Union[str, None] = 'b28d1c90569b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
