"""Change Order

Revision ID: f7dadf932dda
Revises: 7f3f450ef0f2
Create Date: 2023-12-17 20:11:21.922377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7dadf932dda'
down_revision: Union[str, None] = '7f3f450ef0f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('OPENED', 'CLOSED', 'CANCELED', name='orderstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=sa.Enum('OPENED', 'CLOSED', 'CANCELED', name='orderstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
