"""Add constaints

Revision ID: b053c354001c
Revises: d0895b3b294b
Create Date: 2023-12-20 10:14:29.917957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b053c354001c'
down_revision: Union[str, None] = 'd0895b3b294b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_user_id_fkey', 'comment', type_='foreignkey')
    op.drop_constraint('comment_product_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.drop_constraint('order_detail_product_id_fkey', 'order_detail', type_='foreignkey')
    op.drop_constraint('order_detail_order_id_fkey', 'order_detail', type_='foreignkey')
    op.create_foreign_key(None, 'order_detail', 'order', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_detail', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_detail', type_='foreignkey')
    op.drop_constraint(None, 'order_detail', type_='foreignkey')
    op.create_foreign_key('order_detail_order_id_fkey', 'order_detail', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('order_detail_product_id_fkey', 'order_detail', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_product_id_fkey', 'comment', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('comment_user_id_fkey', 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
